/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.ProdutoModelo;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import Controle.IVeiculoControle;

/**
 *
 * @author Andre
 */
public class CadastroProduto extends javax.swing.JFrame {

    ProdutoModelo p=new ProdutoModelo();
    
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        
        campoDescricaoProduto.setEnabled(false);
        campoPrecoProduto.setEnabled(false);
              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoCodigoProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoDescricaoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoPrecoProduto = new javax.swing.JTextField();
        botaoSalvarProduto = new javax.swing.JButton();
        botaoNovoProduto = new javax.swing.JButton();
        botaoVoltarCadastroProduto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botaoPesquisarProduto = new javax.swing.JButton();
        botaoExcluirServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código do Produto");

        campoCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição");

        jLabel3.setText("Preço");

        botaoSalvarProduto.setText("Salvar");
        botaoSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarProdutoActionPerformed(evt);
            }
        });

        botaoNovoProduto.setText("Novo");
        botaoNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoProdutoActionPerformed(evt);
            }
        });

        botaoVoltarCadastroProduto.setText("Voltar");
        botaoVoltarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarCadastroProdutoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Cadastro de Produtos");

        botaoPesquisarProduto.setText("Pesquisar");
        botaoPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarProdutoActionPerformed(evt);
            }
        });

        botaoExcluirServico.setText("Excluir");
        botaoExcluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(botaoVoltarCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(campoPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(242, 242, 242))
                            .addComponent(campoDescricaoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoCodigoProduto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(botaoPesquisarProduto)
                                .addGap(18, 18, 18)
                                .addComponent(botaoExcluirServico))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarProduto)
                    .addComponent(botaoExcluirServico))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarProduto)
                    .addComponent(botaoNovoProduto)
                    .addComponent(botaoVoltarCadastroProduto))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoProdutoActionPerformed
        
        campoDescricaoProduto.setEnabled(true);
        campoPrecoProduto.setEnabled(true);
        
        campoCodigoProduto.setText("");
        
        
        
    }//GEN-LAST:event_botaoNovoProdutoActionPerformed

    private void botaoSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarProdutoActionPerformed
        
        ProdutoModelo p=new ProdutoModelo();
      
        p.setCodProd(Integer.parseInt(campoCodigoProduto.getText()));
        p.setDescricaoPD(campoDescricaoProduto.getText());
        p.setPreco(Float.parseFloat(campoPrecoProduto.getText()));
       
        try {
             Registry registry = LocateRegistry.getRegistry("127.0.0.1",1100);
             IVeiculoControle controle = (IVeiculoControle) registry.lookup("Produto");
             String resultado =  controle.inserirProduto(p);
             System.out.println(resultado);
        } catch (RemoteException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoSalvarProdutoActionPerformed

    private void botaoVoltarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarCadastroProdutoActionPerformed
        CadastroProduto app=new CadastroProduto();
        app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_botaoVoltarCadastroProdutoActionPerformed

    private void botaoPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarProdutoActionPerformed
         
       campoDescricaoProduto.setEnabled(true);
       campoPrecoProduto.setEnabled(true);
        
       ProdutoModelo p= new ProdutoModelo();
       p.setCodProd(Integer.parseInt(campoCodigoProduto.getText()));
      
        try {
             Registry registry = LocateRegistry.getRegistry("127.0.0.1",1100);
             IVeiculoControle controle = (IVeiculoControle) registry.lookup("Produto");
             p =  controle.selecionarProduto(p);
             campoDescricaoProduto.setText(p.getDescricaoPD());
             campoPrecoProduto.setText(String.valueOf(p.getPreco()));
                          
        } catch (RemoteException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoPesquisarProdutoActionPerformed

    private void campoCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoProdutoActionPerformed

    private void botaoExcluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirServicoActionPerformed
        
       ProdutoModelo p= new ProdutoModelo();
       p.setCodProd(Integer.parseInt(campoCodigoProduto.getText()));
      
        try {
             Registry registry = LocateRegistry.getRegistry("127.0.0.1",1100);
             IVeiculoControle controle = (IVeiculoControle) registry.lookup("Produto");
             
             controle.excluir(p);
             
             campoDescricaoProduto.setText(p.getDescricaoPD());
             campoPrecoProduto.setText(String.valueOf(p.getPreco()));
             
        } catch (RemoteException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoExcluirServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluirServico;
    private javax.swing.JButton botaoNovoProduto;
    private javax.swing.JButton botaoPesquisarProduto;
    private javax.swing.JButton botaoSalvarProduto;
    private javax.swing.JButton botaoVoltarCadastroProduto;
    private javax.swing.JTextField campoCodigoProduto;
    private javax.swing.JTextField campoDescricaoProduto;
    private javax.swing.JTextField campoPrecoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
