/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.MotoristaModelo;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import Controle.IMotoristaControle;
import java.sql.Date;

/**
 *
 * @author Andre
 */
public class CadastroOrdemDeServico extends javax.swing.JFrame {

    
    
    /**
     * Creates new form CadastroOrdemDeServico
     */
    public CadastroOrdemDeServico() {
        initComponents();
        
        campoCodigoServicoOrdemDeServico.setEnabled(false);
        campoCodigoClienteOrdemDeServico.setEnabled(false);
        campoDataEntradaOrdemDeServico.setEnabled(false);
        campoDataDeEntregaOrdemDeServico.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoCodigoOrdemDeServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoCodigoClienteOrdemDeServico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCodigoServicoOrdemDeServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoSalvarOrdemDeServico = new javax.swing.JButton();
        botaoVoltarCadastroOs = new javax.swing.JButton();
        botaoNovoOrdemDeServico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoDataDeEntregaOrdemDeServico = new javax.swing.JTextField();
        campoDataEntradaOrdemDeServico = new javax.swing.JTextField();
        botaoPesquisarOrdemDeServico = new javax.swing.JButton();
        botaoExcluirOrdemDeServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código da Ordem de Serviço");

        campoCodigoOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoOrdemDeServicoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código do Cliente");

        jLabel4.setText("Código Serviço");

        jLabel3.setText("Data de Entrada");

        jLabel5.setText("Data de Entrega");

        botaoSalvarOrdemDeServico.setText("Salvar");
        botaoSalvarOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarOrdemDeServicoActionPerformed(evt);
            }
        });

        botaoVoltarCadastroOs.setText("Voltar");
        botaoVoltarCadastroOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarCadastroOsActionPerformed(evt);
            }
        });

        botaoNovoOrdemDeServico.setText("Novo");
        botaoNovoOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoOrdemDeServicoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Cadastro de Ordem de Serviço");

        campoDataDeEntregaOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataDeEntregaOrdemDeServicoActionPerformed(evt);
            }
        });

        botaoPesquisarOrdemDeServico.setText("Pesquisar");
        botaoPesquisarOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarOrdemDeServicoActionPerformed(evt);
            }
        });

        botaoExcluirOrdemDeServico.setText("Excluir");
        botaoExcluirOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirOrdemDeServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoNovoOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(botaoSalvarOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(botaoVoltarCadastroOs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(100, 100, 100))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoDataEntradaOrdemDeServico)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoDataDeEntregaOrdemDeServico)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoCodigoServicoOrdemDeServico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCodigoOrdemDeServico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(botaoPesquisarOrdemDeServico)
                                .addGap(18, 18, 18)
                                .addComponent(botaoExcluirOrdemDeServico))
                            .addComponent(campoCodigoClienteOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigoOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisarOrdemDeServico)
                    .addComponent(botaoExcluirOrdemDeServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodigoServicoOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodigoClienteOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataDeEntregaOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataEntradaOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarOrdemDeServico)
                    .addComponent(botaoVoltarCadastroOs)
                    .addComponent(botaoNovoOrdemDeServico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarOrdemDeServicoActionPerformed

       MotoristaModelo motorista=new MotoristaModelo();
      
        motorista.setCodMotorista(Integer.parseInt(campoCodigoOrdemDeServico.getText()));
        motorista.setNomeMotorista(campoCodigoServicoOrdemDeServico.getText());
        motorista.setCategoriaCNH(campoCodigoClienteOrdemDeServico.getText());
        motorista.setNumeroCNH(Integer.parseInt(campoDataEntradaOrdemDeServico.getText()));
        motorista.setVencimentoCNH(Date.valueOf(campoDataDeEntregaOrdemDeServico.getText()));
        
        try {
             Registry registry = LocateRegistry.getRegistry("127.0.0.1",1100);
             IMotoristaControle controle = (IMotoristaControle) registry.lookup("Motorista");
             String resultado =  controle.inserirMotorista(motorista);
             System.out.println(resultado);
        } catch (RemoteException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoSalvarOrdemDeServicoActionPerformed

    private void botaoVoltarCadastroOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarCadastroOsActionPerformed
        CadastroOrdemDeServico app=new CadastroOrdemDeServico();
        app.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_botaoVoltarCadastroOsActionPerformed

    private void botaoPesquisarOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarOrdemDeServicoActionPerformed
       
       campoCodigoServicoOrdemDeServico.setEnabled(true);
       campoCodigoClienteOrdemDeServico.setEnabled(true);
       campoDataEntradaOrdemDeServico.setEnabled(true);
       campoDataDeEntregaOrdemDeServico.setEnabled(true);
        
       MotoristaModelo motorista= new MotoristaModelo();
       motorista.setCodMotorista(Integer.parseInt(campoCodigoOrdemDeServico.getText()));
       
       
       try {
             Registry registry = LocateRegistry.getRegistry("127.0.0.1",1100);
             IMotoristaControle controle = (IMotoristaControle) registry.lookup("Motorista");
             motorista =  controle.selecionarMotorista(motorista);
             
             campoCodigoServicoOrdemDeServico.setText(String.valueOf(motorista.getNomeMotorista()));
             campoCodigoClienteOrdemDeServico.setText(String.valueOf(motorista.getCategoriaCNH()));
             campoDataEntradaOrdemDeServico.setText(String.valueOf(motorista.getNumeroCNH()));
             campoDataDeEntregaOrdemDeServico.setText(String.valueOf(motorista.getVencimentoCNH()));
             
        } catch (RemoteException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
       
    }//GEN-LAST:event_botaoPesquisarOrdemDeServicoActionPerformed

    private void botaoNovoOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoOrdemDeServicoActionPerformed
        
        campoCodigoServicoOrdemDeServico.setEnabled(true);
        campoCodigoClienteOrdemDeServico.setEnabled(true); // deixa o campo desabilitado
        campoDataEntradaOrdemDeServico.setEnabled(true);
        campoDataDeEntregaOrdemDeServico.setEnabled(true);
        
        campoCodigoOrdemDeServico.setText("");
    }//GEN-LAST:event_botaoNovoOrdemDeServicoActionPerformed

    private void botaoExcluirOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirOrdemDeServicoActionPerformed
        
       MotoristaModelo motorista= new MotoristaModelo();
       motorista.setCodMotorista(Integer.parseInt(campoCodigoOrdemDeServico.getText()));
      
        try {
             Registry registry = LocateRegistry.getRegistry("127.0.0.1",1100);
             IMotoristaControle controle = (IMotoristaControle) registry.lookup("Motorista");
             
             controle.excluir(motorista);
             
             campoCodigoServicoOrdemDeServico.setText(String.valueOf(motorista.getNomeMotorista()));
             campoCodigoClienteOrdemDeServico.setText(String.valueOf(motorista.getCategoriaCNH()));
             campoDataEntradaOrdemDeServico.setText(String.valueOf(motorista.getNumeroCNH()));
             //campoDataDeEntregaOrdemDeServico.setText(String.valueOf(motorista.getVencimentoCNH()));
             
        } catch (RemoteException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoExcluirOrdemDeServicoActionPerformed

    private void campoCodigoOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoOrdemDeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoOrdemDeServicoActionPerformed

    private void campoDataDeEntregaOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataDeEntregaOrdemDeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataDeEntregaOrdemDeServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroOrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOrdemDeServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluirOrdemDeServico;
    private javax.swing.JButton botaoNovoOrdemDeServico;
    private javax.swing.JButton botaoPesquisarOrdemDeServico;
    private javax.swing.JButton botaoSalvarOrdemDeServico;
    private javax.swing.JButton botaoVoltarCadastroOs;
    private javax.swing.JTextField campoCodigoClienteOrdemDeServico;
    private javax.swing.JTextField campoCodigoOrdemDeServico;
    private javax.swing.JTextField campoCodigoServicoOrdemDeServico;
    private javax.swing.JTextField campoDataDeEntregaOrdemDeServico;
    private javax.swing.JTextField campoDataEntradaOrdemDeServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
